"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$kubernetes\
$line_break\
$character"""

[directory]
style = 'blue bold'

[kubernetes]
disabled = false
format = '[$symbol$context($namespace)](dimmed green)'
